### ISSUE TITLE
Разместить отчёт о посещении детей из центра "Семья"

### ISSUE THREAD

**Issue by ghost** [boringplace/boringplace.github.io#10]
*Обновить boringplace.org*:
- [ ] Посещение детей из центра "Семья" перенести в список прошедших мероприятий.
- [ ] Фотографии из скучной беседы разместить в группе скучного места.
- [ ] Оформить страницу отчёта о мероприятии на boringplace.org.

**Comment by gochankot** [comment]
Видио на флешке у sin с собой
